### ISSUE TITLE
Various additions

### ISSUE THREAD

**Issue by nodiscc** [nodiscc/awesome-linuxaudio#22]
Already migrated pages can be found in `DONE.md`
#### TODO
- [ ] **http://wiki.linuxaudio.org/apps/start**
- [ ] http://bandshed.net/avlinux6-debs/
- [ ] http://ccmixter.org/
- [ ] http://ccrma.stanford.edu/planetccrma/software/
- [ ] http://djcj.org/audio/lam/
- [ ] http://dssi.sourceforge.net/
- [ ] http://freepats.zenvoid.org/
- [ ] http://gareus.org/blog/jack2dbus
- [ ] http://jackaudio.org/
- [x] http://jackaudio.org/applications/
- [ ] http://jackaudio.org/faq/
- [ ] http://kxstudio.linuxaudio.org/Repositories:Applications
- [ ] http://kxstudio.linuxaudio.org/Repositories:Plugins
- [ ] http://lam.fugal.net/
- [ ] http://lapoc.de/samples/
- [ ] http://sunsite.univie.ac.at/Linux-soundapp/one-page.html
- [ ] http://linux-audio.com/audio_quality_howto.htm
- [ ] http://linux-audio.com/evolution-usb-midi.php
- [ ] http://linux-audio.com/ice1712multi.html
- [ ] http://linux-audio.com/jack/
- [ ] http://linux-audio.com/Sound-HOWTO.html
- [ ] http://linux-audio.com/Sound-Playing-HOWTO.html
- [ ] http://linux-audio.com/TiMidity-howto.html
- [ ] http://linuxaudio.org/
- [ ] http://opensourcemusician.com/index.php/Software
- [x] http://plus24.com/mp3-howto/mp3-howto.html
- [ ] http://proaudio.tuxfamily.org/wiki/index.php?title=Main_Page
- [ ] http://sound.condorow.net/
- [ ] http://sso.mattiaswestlund.net/
- [ ] http://tldp.org/
- [ ] http://tldp.org/docs.html#howto
- [ ] http://videos.linux-audio.com/
- [ ] http://wiki.linuxaudio.org/
- [ ] http://wiki.linuxaudio.org/apps/all
- [ ] http://wiki.linuxaudio.org/apps/categories/start
- [ ] http://wiki.linuxaudio.org/apps/categories/start?do=index
- [ ] http://wiki.linuxaudio.org/apps/categories/start?idx=hw
- [ ] http://wiki.linuxaudio.org/hw/start
- [ ] http://wiki.linuxaudio.org/wiki/alesis_io2_express
- [ ] http://wiki.linuxaudio.org/wiki/free_audio_data
- [ ] http://wiki.linuxaudio.org/wiki/hardware
- [ ] http://wiki.linuxaudio.org/wiki/linux_audio_applications
- [ ] http://wiki.linuxaudio.org/wiki/migrationprogress
- [ ] http://wiki.linuxaudio.org/wiki/real_time_info
- [ ] http://wiki.linuxaudio.org/wiki/start
- [ ] http://wiki.linuxaudio.org/wiki/system_configuration
- [ ] http://wiki.linuxaudio.org/wiki/vst_support_and_commercial_apps
- [ ] http://www.4front-tech.com/index.html
- [ ] http://www.64studio.com/
- [ ] http://www.bandshed.net/
- [ ] http://www.ibiblio.org/pub/Linux/apps/sound/editors/!INDEX.html
- [ ] http://www.kvraudio.com/news/discodsp-updates-discovery-pro-va-and-wave-synth-to-6-4-5-29782
- [ ] http://www.kvraudio.com/news/discodsp-updates-vertigo-additive-synth-to-r3-5-including-linux-support-29997
- [ ] http://www.kvraudio.com/plugins/linux/newest
- [ ] http://www.linux-sound.org/
- [ ] http://www.linuxlinks.com/article/20080622143124178/Audio.html
- [ ] http://www.linuxmao.org/Accueil
- [ ] http://www.linuxsynths.com/
- [ ] http://www.opensound.com/
- [ ] http://www.orford.org/assets/jack-idiots_guide.txt
- [ ] http://www.plus24.com/midi-howto/index.html
- [ ] https://alsa-project.org/main/index.php/Matrix:Main
- [ ] https://alsa-project.org/wiki/Main_Page
- [ ] https://alsa.opensrc.org/
- [ ] https://archive.org/details/audio
- [ ] https://bandcamp.com/tag/linux?artist=1485551842
- [ ] https://didjix.blogspot.com/ dead 2016
- [ ] https://discourse.ardour.org/t/ardour-setup-images/78327
- [ ] https://distrho.sourceforge.io/
- [ ] https://en.wikipedia.org/wiki/Comparison_of_free_software_for_audio
- [ ] https://en.wikipedia.org/wiki/List_of_Ambisonic_Software
- [ ] https://en.wikipedia.org/wiki/List_of_Linux_audio_software
- [ ] https://en.wikipedia.org/wiki/List_of_Linux_audio_software
- [ ] https://fedoraproject.org/wiki/Fedora_jam
- [ ] https://freesound.org/
- [ ] https://github.com/nodiscc/dbu/blob/master/build/config/package-lists/audacity.list.chroot
- [ ] https://joindiaspora.com/tags/linuxaudio
- [ ] https://linuxmao.org/Accueil
- [ ] https://linuxmusicians.com/
- [ ] https://lists.columbia.edu/mailman/listinfo/andraudio
- [ ] https://lmms.io/lsp/index.php
- [ ] https://news.google.com/?pz=1&jfkl=true&cf=all&csid=7761883e5c5cb9b3&ict=ln&hl=en-US&gl=US&ceid=US:en
- [ ] https://planet.linuxaudio.org/
- [ ] https://rt.wiki.kernel.org/index.php/Main_Page
- [ ] https://twitter.com/linuxsound
- [ ] https://ubuntustudio.org/
- [ ] https://wiki.linuxaudio.org/apps/categories/linux_audio_bundles_distributions
- [ ] https://wiki.linuxaudio.org/faq/start?redirect=1
- [ ] https://wiki.linuxaudio.org/wiki/lowlatency_deprecated
- [ ] https://wiki.linuxaudio.org/wiki/lowlatency_deprecated
- [ ] https://wiki.linuxaudio.org/wiki/start
- [ ] https://wiki.linuxaudio.org/wiki/tutorials/start
- [ ] https://wiki.multimedia.cx/index.php/Main_Page
- [ ] https://www.audio4linux.de/forum/
- [ ] https://www.facebook.com/home.php?sk=group_189734702059
- [ ] https://www.freedesktop.org/wiki/Software/PulseAudio/
- [ ] https://www.ladspa.org/
- [ ] https://www.linuxjournal.com/users/dave-phillips
- [ ] https://www.youtube.com/results?search_query=linux+audio&aq=f
- [ ] Linux basics: wiki.debian.org
- [x] http://giss.tv/
- [x] http://jackaudio.org/applications/
- [x] http://linux-audio.com/
- [x] http://linux-sound.org/one-page.html
- [x] http://quicktoots.linux-audio.com/
- [x] http://www.ibiblio.org/pub/Linux/apps/sound/editors/
- [x] https://gist.github.com/nodiscc/f8ef6744199ec9f26044
- [x] https://github.com/coderofsalvation/audiobrowse.bash

**Comment by nodiscc** [comment]
- [ ] https://packages.debian.org/search?keywords=goattracker
 - [ ] http://www.gp2x.org/remid/
 - [ ] http://energyxt2.wikidot.com/
 - [ ] https://sites.google.com/site/neilsequencer/

**Comment by nodiscc** [comment]
http://spectmorph.org/

**Comment by nodiscc** [comment]
https://github.com/lucianodato/noise-repellent

**Comment by salvadhor** [comment]
Ocenaudio:

https://www.ocenaudio.com/

**Comment by nodiscc** [comment]
- https://github.com/x42/lv2vst
- https://github.com/osxmidi/SFZero/

**Comment by nodiscc** [comment]
https://github.com/brummer10/Mamba

**Comment by nodiscc** [comment]
https://packages.debian.org/sid/qwertone

**Comment by nodiscc** [comment]
Moved to https://gitlab.com/nodiscc/awesome-linuxaudio/-/issues/1
